07-08-2025 v2

diff --git a/files/openvpn b/files/openvpn
--- a/files/openvpn
+++ b/files/openvpn
@@ -1,30 +1,81 @@
 #!/bin/bash
+
 export DEBIAN_FRONTEND=noninteractive
-OS=`uname -m`;
-MYIP=$(wget -qO- ipinfo.io/ip);
-domain=$(cat /root/domain)
-MYIP2="s/xxxxxxxxx/$domain/g";
-function ovpn_install() {
-rm -rf /etc/openvpn
-mkdir -p /etc/openvpn
-wget -O /etc/openvpn/vpn.zip "https://raw.githubusercontent.com/zxeeds/vip-script/main/ovpn/vpn.zip" >/dev/null 2>&1
-unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip
-rm -f /etc/openvpn/vpn.zip
-chown -R root:root /etc/openvpn/server/easy-rsa/
+
+set -e
+
+# Helper color
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
+
+log() { echo -e "${GREEN}[INFO]${NC} $1"; }
+error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }
+
+# Check Dependencies
+check_dep() {
+  command -v "$1" >/dev/null 2>&1 || { error "Dependency '$1' is not installed! Install it first!"; }
 }
-function config_easy() {
-cd
-mkdir -p /usr/lib/openvpn/
-cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
-sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
-systemctl enable --now openvpn-server@server-tcp
-systemctl enable --now openvpn-server@server-udp
-/etc/init.d/openvpn restart
+
+check_dep "wget"
+check_dep "unzip"
+check_dep "systemctl"
+check_dep "curl"
+
+# Ensure OpenVPN installed
+if ! dpkg -s openvpn 2>/dev/null | grep -q "Status: install"; then
+  log "Installing OpenVPN..."
+  apt update
+  apt install openvpn -y
+fi
+
+# Ensure plugin PAM exists
+PLUGIN_SRC="/usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so"
+PLUGIN_DST="/usr/lib/openvpn/openvpn-plugin-auth-pam.so"
+if [ ! -f "$PLUGIN_SRC" ]; then
+  error "OpenVPN PAM plugin not found at $PLUGIN_SRC! Is OpenVPN installed correctly?"
+fi
+
+# Ensure domain file exists
+DOMAIN_FILE="/etc/xray/domain"
+if [ ! -f "$DOMAIN_FILE" ]; then
+  error "Domain file not found at $DOMAIN_FILE! Please create and fill with your domain or IP."
+fi
+
+domain=$(cat $DOMAIN_FILE)
+MYIP2="s/xxxxxxxxx/$domain/g"
+
+ovpn_install() {
+  log "Preparing OpenVPN config..."
+  rm -rf /etc/openvpn
+  mkdir -p /etc/openvpn
+  wget -O /etc/openvpn/vpn.zip "https://raw.githubusercontent.com/zxeeds/VipScript-v3/main/ovpn/vpn.zip"
+  unzip -d /etc/openvpn/ /etc/openvpn/vpn.zip
+  rm -f /etc/openvpn/vpn.zip
+  chown -R root:root /etc/openvpn/server/easy-rsa/
 }
-function make_follow() {
-echo 1 > /proc/sys/net/ipv4/ip_forward
-sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
-cat > /etc/openvpn/tcp.ovpn <<-END
+
+config_easy() {
+  log "Configuring Easy-RSA and PAM plugin..."
+  mkdir -p /usr/lib/openvpn/
+  cp "$PLUGIN_SRC" "$PLUGIN_DST"
+  if [ -f /etc/default/openvpn ]; then
+    sed -i 's/#AUTOSTART="all"/AUTOSTART="all"/g' /etc/default/openvpn
+  else
+    echo 'AUTOSTART="all"' > /etc/default/openvpn
+  fi
+  systemctl enable --now openvpn-server@server-tcp || log "Service openvpn-server@server-tcp not found, skip enable"
+  systemctl enable --now openvpn-server@server-udp || log "Service openvpn-server@server-udp not found, skip enable"
+  systemctl restart openvpn || log "Service openvpn not found, skip restart"
+}
+
+make_follow() {
+  log "Setting up IP forwarding and sysctl..."
+  echo 1 > /proc/sys/net/ipv4/ip_forward
+  sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
+  sysctl -p
+  # Generate OVPN client configs
+  cat > /etc/openvpn/tcp.ovpn <<-END
 client
 dev tun
 proto tcp
@@ -38,8 +89,8 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-sed -i $MYIP2 /etc/openvpn/tcp.ovpn;
-cat > /etc/openvpn/udp.ovpn <<-END
+  sed -i $MYIP2 /etc/openvpn/tcp.ovpn;
+  cat > /etc/openvpn/udp.ovpn <<-END
 client
 dev tun
 proto udp
@@ -53,8 +104,8 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-sed -i $MYIP2 /etc/openvpn/udp.ovpn;
-cat > /etc/openvpn/ws-ssl.ovpn <<-END
+  sed -i $MYIP2 /etc/openvpn/udp.ovpn;
+  cat > /etc/openvpn/ws-ssl.ovpn <<-END
 client
 dev tun
 proto tcp
@@ -68,8 +119,8 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-sed -i $MYIP2 /etc/openvpn/ws-ssl.ovpn;
-cat > /etc/openvpn/ssl.ovpn <<-END
+  sed -i $MYIP2 /etc/openvpn/ws-ssl.ovpn;
+  cat > /etc/openvpn/ssl.ovpn <<-END
 client
 dev tun
 proto tcp
@@ -83,48 +134,85 @@ auth-user-pass
 comp-lzo
 verb 3
 END
-sed -i $MYIP2 /etc/openvpn/ssl.ovpn;
+  sed -i $MYIP2 /etc/openvpn/ssl.ovpn;
 }
-function cert_ovpn() {
-echo '<ca>' >> /etc/openvpn/tcp.ovpn
-cat /etc/openvpn/server/ca.crt >> /etc/openvpn/tcp.ovpn
-echo '</ca>' >> /etc/openvpn/tcp.ovpn
-cp /etc/openvpn/tcp.ovpn /var/www/html/tcp.ovpn
-echo '<ca>' >> /etc/openvpn/udp.ovpn
-cat /etc/openvpn/server/ca.crt >> /etc/openvpn/udp.ovpn
-echo '</ca>' >> /etc/openvpn/udp.ovpn
-cp /etc/openvpn/udp.ovpn /var/www/html/udp.ovpn
-echo '<ca>' >> /etc/openvpn/ws-ssl.ovpn
-cat /etc/openvpn/server/ca.crt >> /etc/openvpn/ws-ssl.ovpn
-echo '</ca>' >> /etc/openvpn/ws-ssl.ovpn
-cp /etc/openvpn/ws-ssl.ovpn /var/www/html/ws-ssl.ovpn
-echo '</ca>' >> /etc/openvpn/ssl.ovpn
-cp /etc/openvpn/ws-ssl.ovpn /var/www/html/ssl.ovpn
-cd /var/www/html/
-zip Kyt-Project.zip tcp.ovpn udp.ovpn ssl.ovpn ws-ssl.ovpn > /dev/null 2>&1
-cd
-cat <<'mySiteOvpn' > /var/www/html/index.html
+
+cert_ovpn() {
+  log "Embedding CA certificate to OVPN client configs..."
+  for c in tcp udp ws-ssl ssl; do
+    echo '<ca>' >> /etc/openvpn/${c}.ovpn
+    cat /etc/openvpn/server/ca.crt >> /etc/openvpn/${c}.ovpn
+    echo '</ca>' >> /etc/openvpn/${c}.ovpn
+    cp /etc/openvpn/${c}.ovpn /var/www/html/${c}.ovpn
+  done
+  cd /var/www/html/
+  zip Kyt-Project.zip tcp.ovpn udp.ovpn ssl.ovpn ws-ssl.ovpn > /dev/null 2>&1
+  cd
+  # Generate HTML download page
+  cat <<'mySiteOvpn' > /var/www/html/index.html
 <!DOCTYPE html>
 <html lang="en">
-<!-- Simple OVPN Download site -->
-<head><meta charset="utf-8" /><title>OVPN Config Download</title><meta name="description" content="Server" /><meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" /><meta name="theme-color" content="#000000" /><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"><link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet"></head><body><div class="container justify-content-center" style="margin-top:9em;margin-bottom:5em;"><div class="col-md"><div class="view"><img src="https://openvpn.net/wp-content/uploads/openvpn.jpg" class="card-img-top"><div class="mask rgba-white-slight"></div></div><div class="card"><div class="card-body"><h5 class="card-title">Config List</h5><br /><ul class="list-group">
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>TCP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/tcp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>UDP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/udp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p>SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p> WS SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ws-ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-<li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;"><p> ALL.zip <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span><br /><small></small></p><a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/Kyt-Project.zip" style="float:right;"><i class="fa fa-download"></i> Download</a></li>
-</ul></div></div></div></div></body></html>
+<head>
+  <meta charset="utf-8" />
+  <title>OVPN Config Download</title>
+  <meta name="description" content="Server" />
+  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
+  <meta name="theme-color" content="#000000" />
+  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
+  <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
+  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.3/css/mdb.min.css" rel="stylesheet">
+</head>
+<body>
+  <div class="container justify-content-center" style="margin-top:9em;margin-bottom:5em;">
+    <div class="col-md">
+      <div class="view">
+        <img src="https://openvpn.net/wp-content/uploads/openvpn.jpg" class="card-img-top">
+        <div class="mask rgba-white-slight"></div>
+      </div>
+      <div class="card">
+        <div class="card-body">
+          <h5 class="card-title">Config List</h5><br />
+          <ul class="list-group">
+            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+              <p>TCP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span></p>
+              <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/tcp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a>
+            </li>
+            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+              <p>UDP <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span></p>
+              <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/udp.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a>
+            </li>
+            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+              <p>SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span></p>
+              <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a>
+            </li>
+            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+              <p>WS SSL <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span></p>
+              <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/ws-ssl.ovpn" style="float:right;"><i class="fa fa-download"></i> Download</a>
+            </li>
+            <li class="list-group-item justify-content-between align-items-center" style="margin-bottom:1em;">
+              <p>ALL.zip <span class="badge light-blue darken-4">Android/iOS/PC/Modem</span></p>
+              <a class="btn btn-outline-success waves-effect btn-sm" href="https://IP-ADDRESSS:81/Kyt-Project.zip" style="float:right;"><i class="fa fa-download"></i> Download</a>
+            </li>
+          </ul>
+        </div>
+      </div>
+    </div>
+  </div>
+</body>
+</html>
 mySiteOvpn
-sed -i "s|IP-ADDRESSS|$(curl -sS ifconfig.me)|g" /var/www/html/index.html
+  sed -i "s|IP-ADDRESSS|$(curl -sS ifconfig.me)|g" /var/www/html/index.html
 }
-function install_ovpn() {
-ovpn_install
-config_easy
-make_follow
-make_follow
-cert_ovpn
-systemctl enable openvpn
-systemctl start openvpn
-/etc/init.d/openvpn restart
+
+install_ovpn() {
+  ovpn_install
+  config_easy
+  make_follow
+  cert_ovpn
+  systemctl enable openvpn
+  systemctl start openvpn
+  systemctl restart openvpn
+  log "OpenVPN installation and configuration completed!"
 }
+
 install_ovpn
